apiVersion: configsync.gke.io/v1beta1
kind: RootSync
metadata:
  name: root-sync
  namespace: config-management-system
spec:
  git:
    repo: https://github.com/ejmadkins/acm-rootrepo
    branch: main
    dir: "acm-config"
    auth: none