apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: front-end-inbound
spec:
  podSelector:
    matchLabels:
      tier: front-end
  policyTypes:
  - Ingress
  ingress:
  - from:
    - ipBlock:
        cidr: 0.0.0.0/0
    ports:
    - protocol: TCP
      port: 80
